GospelWorld/Entities/Sermon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GospelWorld.Entities
{
    public class Sermon
    {
        [Key]
        public int SermId { get; set; }
        public int? CatId { get; set; }

        public string PreacherName { get; set; }
        public string SermonText { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string SermonTitle { get; set; }
        public DateTime SermonDate { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnailUrl { get; set; }
        //public string SermonvideoUrl { get; set; }
        // public string SermonvideoThumbnail { get; set; }

        public bool IsLiked { get; set; }
        public virtual SermonCategory SermonCategory { get; set; }
  


    }
}

GospelWorld/Controllers/SermonController.cs
using GospelWorld.Entities;
using GospelWorld.Interface;
using GospelWorld.Models;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GospelWorld.Controllers
{
    public class SermonController : Controller
    {
    private ISermonServices  _sermonServices;
        private ApplicationDbContext _context;
        public SermonController (ISermonServices sermonServices)
        {
            _sermonServices = sermonServices;
            _context = new ApplicationDbContext();

        }

        // GET: Sermon
        public ActionResult Index()
        {
            var sermon = _sermonServices.GetSermons().OrderBy(n =>n.SermonDate);
            ViewBag.SermonCategory = _context.SermonCategories.ToList().Select(r => new SermonCategoryModel(r)
            {
                  SermonDescription = r.SermonDescription,
                   SermonName = r.SermonName
            });

            var sermonCat = _context.SermonCategories.ToList();
         
            var svm = new  SermonViewModel
            {
                 Sermons = sermon,
                SermonCategorss = sermonCat,
                SermonCat = ""

            };
            return View(svm);
        }

        public ActionResult BibleTestss(SermonModel model)
        {
            var results = _sermonServices.GetAllBibleTest(model);
            
            return View(results);


        }

        public ActionResult PrintPdf (SermonModel model)
        {
            var svm = new SermonIndexViewModel
            {
                sermon = model
            };
            var pdfView = new ViewAsPdf("SermonDetails", svm)
            {
                FileName = "File.pdf",
                PageSize = Rotativa.Options.Size.A4,
                PageMargins =
                {
                    Left=0,
                    Right=0
                }
            };
            return pdfView;
        }
        public ActionResult SermonsbyCategory(string name)
        {
            var sermonscategory = _sermonServices.GetSermons().Where(vv => vv.SermonCategory.SermonName == name);

            var svm = new SermonViewModel
            {
               Sermons = sermonscategory,
                SermonCat = name
            };
            return View("Index", svm);
        }
        public ActionResult SermonDetails(int id = 0)
        {

            var _sermon = _context.Sermons.Find(id);
            var result = _sermonServices.GetSermonById(id);
            var sermon = _sermon;
            //var sivm = new SermonIndexViewModel
            //{
            //    sermon = sermon,
            //    ReturnUrl = returnurl
            //};
            return View(sermon);
        }
    }
}

GospelWorld/Views/Sermon/BibleTestss.cshtml
@model GospelWorld.Models.SermonModel
@{
    ViewBag.Title = "BibleTestss";
}

<h2>BibleTestss</h2>

<form>
    
</form>

GospelWorld/Views/Sermon/Index.cshtml
@using GospelWorld.Models
@model GospelWorld.Models.SermonViewModel

@{
    ViewBag.Title = "";

}

<div class="breadcumb-area bg-img" style="background-image: url(~/Content/img/bg-img/bg-6.jpg);">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 col-md-6">
                <div class="breadcumb-text">
                    <h5>Live from church</h5>
                    <h2>Sermons</h2>
                    <p>Cras iaculis eleifend arcu, non cursus sem. Morbi viverra varius nisl, ac varius mauris interdum sit amet. Aenean ac fermentum neque.</p>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="sermons-area section-padding-100-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center mx-auto">
                    <img src="~/Content/img/core-img/cross.png" alt="">
                    <h3>The Sermons</h3>
                    <p>Donec quis metus ac arcu luctus accumsan. Nunc in justo tincidunt, sodales nunc id, finibus nibh.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12 col-lg-6 mb-100">

                @foreach (var item in Model.SermonCategorss)
                {
                    <div class="single-sermons style-2">
                        <div class="sermons-content">

                            <div class="sermons-thumbnail bg-img" style="background-image: url(~/Content/img/bg-img/ser9.jpg);"></div>

                            <div class="sermons-text">
                                @Html.ActionLink(item.SermonName, "SermonsbyCategory", "Sermon", new { name = item.SermonName }, new { @class = "" })


                                <p>@item.SermonDescription</p>
                            </div>
                        </div>

                        <div class="sermons-audio-player d-flex align-items-center">
                            <audio preload="auto" controls>
                                <source src="~/Content/audio/dummy-audio.mp3">
                            </audio>
                            <div class="see-more-btn">
                                <a href="@Url.Action("SermonDetails","Sermon", new { id = item.CatId } )">See More</a>
                            </div>
                        </div>
                    </div>

                }

            </div>
            <div class="col-12 col-lg-6 mb-100">

                @foreach (var sermon in Model.Sermons)
                {
                    <div class="single-sermons">
                        <div class="sermons-content d-flex align-items-center">

                            <div class="sermons-thumbnail bg-img">
                                <img src="~/Content/img/blog-img/3.jpg" alt="">
                                <img src="@Url.Content("~/Content/Images/")@sermon.ImageThumbnailUrl" alt="preacher :@sermon.PreacherName" />
                            </div>

                            <div class="sermons-text">
                                <a href="@Url.Action("SermonDetails","Sermon", new { id = sermon.SermId } )">

                                    <h6>@sermon.SermonTitle</h6>
                                </a>
                                <p>by @sermon.PreacherName</p>
                                <p class="date"> @sermon.SermonDate.Date</p>

                            </div>
                        </div>
                    </div>


                }


            </div>
        </div>
    </div>
</section>


<div class="faith-cta-area style-2">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="cta-text d-flex justify-content-between align-items-center">
                    <h5>Most Recent Sermon</h5>

                </div>
            </div>
        </div>
    </div>
</div>



<div class="single-sermons style-3">

    @foreach (var sermon in Model.Sermons)
    {
        if (sermon.SermonDate >= DateTime.Now)
        {
            <div class="sermons-content d-flex align-items-center">

                <div class="sermons-thumbnail bg-img">
                    <img src="@Url.Content("~/Content/Images/")@sermon.ImageThumbnailUrl" alt="preacher :@sermon.PreacherName" />
                </div>
                <div class="sermons-text">
                    <a href="@Url.Action("SermonDetails", "Sermon", new { id = sermon.SermId })">

                        <h6>@sermon.SermonTitle</h6>
                    </a>
                    <p>by @sermon.PreacherName</p>
                    <p class="date"> @sermon.SermonDate.Date</p>
                    <p class="text">@sermon.ShortDescription</p>
                </div>

                <div class="sermons-audio-player mt-70 d-flex align-items-center">
                    <audio preload="auto" controls>
                        <source src="~/Content/audio/dummy-audio.mp3">
                    </audio>
                    <div class="see-more-btn">
                        <a href="#">See More</a>
                    </div>
                </div>

            </div>
            break;
        }
    }
</div>

GospelWorld/Views/Sermon/SermonDetails.cshtml
@model GospelWorld.Models.SermonModel

@{
    ViewBag.Title = "SermonDetails";

}


<div class="main" role="main">
    <div id="content" class="content full">
        <div class="container">
            <div class="row">
                <div class="col-md-8">

                    <h5><span>@Model.SermonTitle</span></h5>
                    <span class="meta-data">Text: @Model.SermonText</span>
                    <div class="sermon-media clearfix">

                        <div class="sermon-media-right">
                            <div class="sermon-media-content">

                                <div class="latest-sermon-content sermon-tabs" id="self-audio">
                                    <blockquote>
                                        <p>@Html.Raw(Model.LongDescription)</p>
                                    </blockquote>
                                </div>
                            </div>
                            <p>@Html.Raw(Model.LongDescription)</p>
                            @Html.ActionLink("Print", "PrintPdf", null, new { @class = "btn btn-primary" }) <div class="social-share-bar">

                                <a href="@Url.Action("Index","Sermon")" class="basic-link backward">Back to series</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="widget sidebar-widget widget_sermon_speakers">
                        <h3 class="widgettitle">Sermon Speakers <span>@Model.PreacherName</span></h3>
                        <ul>
                            <li>
                                <a href="@Url.Action("SermonDetails","Sermon", new { id = Model.SermId } )" class="media-box">
                                    <img src="@Url.Content("~/Content/Images/")@Model.ImageThumbnailUrl" class="img-thumbnail transition" alt="sermons/@Model.PreacherName" />
                                </a>
                            </li>
                            <li>
                                <p> @Model.SermonDate.Date</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>