GospelWorld/Entities/Worker.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GospelWorld.Entities
{
    public class Worker
    {
        [Key]
        public int WorkId { get; set; }
        public int? DeptId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherName { get; set; }
        public string WorkerName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string ImageUrl { get; set; }
        public string ImageThumbnailUrl { get; set; }

       
        public virtual Department Department { get; set; }
        public virtual ICollection<Attendance> Attendancss { get; set; }


    }
}

GospelWorld/Controllers/WorkerController.cs
using GospelWorld.Entities;
using GospelWorld.Interface;
using GospelWorld.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GospelWorld.Controllers
{
    public class WorkerController : Controller
    {
        private ApplicationDbContext _context;
        private IWorkerServices _workServ;
        private IDepartmentService _dptservice;
        public WorkerController( IWorkerServices workerServices, ApplicationDbContext context, IDepartmentService department)
        {
            _context = context;
            _workServ = workerServices;
            _dptservice = department;
        }

        // GET: Worker
        //public ActionResult Index()
        //{

        //    return View();
        //}
        [HttpGet]
        public ActionResult JoinWorker()
        {
            //var dept = _context.Departments.ToList().Select(r => r.DeptName);


            //ViewBag.Department = new SelectList(dept);
            ViewBag.Department = new SelectList(_dptservice.GetDepartments(), "DeptId", "DeptName");

            return View(new WorkerModel());
        }
       // [ValidateInput(false)]
        [HttpPost]
        public ActionResult JoinWorker( WorkerModel model)
        {
            if(ModelState.IsValid)
            {
                ViewBag.Department = new SelectList(_dptservice.GetDepartments(), "DeptId", "DeptName");
             //   var dept = _context.Departments.ToList().Select(r => r.DeptName);
                //ViewBag.Department = new SelectList(dept);
                //  ViewBag.Department = new SelectList(dept);

                // var dept = _workServ.CreateWorker(model);
                string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                string extension = Path.GetExtension(model.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssffff") + extension;
                model.ImageUrl = fileName;
                fileName = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);

                model.ImageFile.SaveAs(fileName);


                var result = _workServ.CreateWorker(model);
                //var worker = new Worker
                //{
                //    //WorkerName = model.FirstName + " " + model.LastName,
                //    FirstName = model.FirstName,
                //    LastName = model.LastName,
                //    Address = model.Address,
                //    DeptId = model.DeptId,
                //    ImageUrl = model.ImageUrl,
                //    ImageThumbnailUrl = model.ImageUrl,
                //    PhoneNumber = model.PhoneNumber
                //};
                if (result != null)
                {
                    //_context.Workers.Add(worker);
                    //_context.SaveChanges();
                    TempData["message"] = string.Format("{0} has been saved.", model.FirstName);
                    return RedirectToAction("Index", "Sermon");
                }
                else
                {
                    var deptl = _dptservice.GetDepartments().Select(r => r.DeptName);
                    ViewBag.Department = new SelectList(deptl);
               
                }

            }


            return View(model);
        }
    }
}

GospelWorld/Views/Worker/JoinWorker.cshtml
@model GospelWorld.Models.WorkerModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Join Us";
}

<div class="breadcumb-area bg-img" style="background-image: url(~/Content/img/bg-img/bg-6.jpg);">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 col-md-6">
                <div class="breadcumb-text">
                    <h5>Join the work force</h5>

                    <p></p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="col-12 col-lg-6">
    <div class="contact-form-area">

        @using (Html.BeginForm("JoinWorker", "Worker", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <hr />
            @*<input type="hidden" name="WorkId" value="@Model.WorkId" />*@
            @Html.HiddenFor(model => model.WorkId)
            <input type="text" class="form-control" name="FirstName" placeholder="Surname" required />
            <input type="text" class="form-control" name="LastName" placeholder="First Name" required />
            <input type="text" class="form-control" name="PhoneNumber" placeholder="Phone Number" required />
            <input type="email" class="form-control" name="email" placeholder="E-mail" />
            <input type="text" class="form-control" name="Address" placeholder="House Address" required />
            <input type="file" name="ImageFile" class="imgInp form-control" accept=".png,.jpg,.jpeg,.gif,.tif" required placeholder="Upload Picture" />


            @Html.DropDownListFor(model => model.DeptId, (IEnumerable<SelectListItem>)ViewBag.Department, "Select a department", new { })


            <textarea name="message" class="form-control" cols="30" rows="10" placeholder="Message"></textarea>
            <input type="submit" value="Save" class="btn btn-default" />
        }
    </div>
</div>